- name: Install the puppet repo package [yum]
  yum: "name=http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm"
  sudo: yes

- name: Install all the required packaes for a puppetmaster [yum]
  yum: "name={{item}} state=present"
  sudo: yes
  with_items: [
    "puppet-server",
    "puppetdb",
    "hiera",
    "facter",
    "puppetdb-terminus",
    "git"
    ]

- name: install r10k
  command: gem install --verbose r10k creates="/usr/bin/r10k"
  sudo: yes

- name: Start the puppetmaster service
  service: "name=puppetmaster state=restarted"
  sudo: yes

#- name: "puppetmaster must have a /etc/hosts entry"
  #lineinfile: dest=/etc/hosts line="127.0.0.1 puppet puppetmaster" state=present 
  #
- name: puppet agent --test
  command: puppet agent --test --server {{ansible_fqdn}} creates="/var/lib/puppet/ssl/certs/{{ ansible_fqdn }}"
  sudo: yes

- name: puppetdb ssl-setup
  command: puppetdb ssl-setup creates="/etc/puppetdb/ssl"
  sudo: yes

- name: Install default hiera.conf
  template: src=hiera.conf.j2 dest=/etc/puppet/hiera.conf owner=root group=root mode=0644
  sudo: yes

- name: Install default puppet.conf
  template: src=puppet.conf.j2 dest=/etc/puppet/puppet.conf owner=root group=root mode=0644
  sudo: yes

- name: Install default puppetdb.conf
  template: src=puppetdb.conf.j2 dest=/etc/puppet/puppetdb.conf owner=root group=root mode=0644
  sudo: yes

- name: Install default routes.yaml
  template: src=routes.yaml.j2 dest=/etc/puppet/routes.yaml owner=root group=root mode=0644
  sudo: yes

- name: Install default r10k.yaml
  template: src=r10k.yaml.j2 dest=/etc/r10k.yaml owner=root group=root mode=0644
  sudo: yes

- name: r10k deploy
  command: r10k deploy environment creates="/etc/puppet/environments/master"
  sudo: yes

- name: install puppet-lint
  gem: name=puppet-lint
  sudo: yes  

- name: Start all the services.
  service: "name={{item}} state=restarted"
  sudo: yes
  with_items: [
    "puppetmaster",
    "puppetdb",
  ]
