# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.forward_agent = true

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  config.vm.define :puppet do |puppet|
    puppet.vm.box = "centos7-puppet"
    puppet.vm.network :private_network, ip: "192.168.33.20"
    puppet.vm.hostname = "puppet.local"
    puppet.hostmanager.aliases = %w(puppet.local puppet)
  end

end

